[book]
title = "Adwaith's CTF Writeups"
description = "Security research, CTF solutions, and exploits."
authors = ["Adwaith Shan"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/Adwaith-Shan-Pk/ctf-writeups"
edit-url-template = "https://github.com/Adwaith-Shan-Pk/ctf-writeups/edit/main/{path}"
additional-css = ["src/custom.css"]
mathjax-support = true
smart-punctuation = true 
copy-fonts = true

[output.html.search]
enable = true
limit_results = 15